"""KAT + property tests for AIGRP pair-secret derivation (Decision 28 §1.1).

The pair-secret HKDF is the cryptographic kernel of intra-Enterprise
peer trust; if these change behaviour silently every L2 in the fleet
suddenly disagrees on its peer secrets. KAT vectors lock the output
bytes for fixed inputs so any future refactor that breaks compatibility
fails loudly.
"""

from __future__ import annotations

import pytest

from cq_server.aigrp.pair_secret import derive_pair_secret, lex_min_canonical


class TestLexMinCanonical:
    def test_orders_lexicographically(self) -> None:
        assert lex_min_canonical("aaa", "bbb") == b"aigrp-pair:aaa:bbb"
        # Reversing inputs gives identical bytes.
        assert lex_min_canonical("bbb", "aaa") == b"aigrp-pair:aaa:bbb"

    def test_unicode_safe(self) -> None:
        # UTF-8 encoded; comparison is on string lex order.
        out = lex_min_canonical("αα", "ββ")
        # Both encode to UTF-8; order is by code point so α (U+03B1) < β (U+03B2).
        assert out == b"aigrp-pair:" + "αα".encode() + b":" + "ββ".encode()

    def test_self_pair_rejected(self) -> None:
        with pytest.raises(ValueError, match="distinct"):
            lex_min_canonical("same", "same")

    def test_empty_rejected(self) -> None:
        with pytest.raises(ValueError, match="non-empty"):
            lex_min_canonical("", "x")
        with pytest.raises(ValueError, match="non-empty"):
            lex_min_canonical("x", "")


class TestDerivePairSecret:
    ROOT_A = bytes.fromhex("00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff")

    def test_deterministic(self) -> None:
        s1 = derive_pair_secret(self.ROOT_A, "ent/x", "ent/y")
        s2 = derive_pair_secret(self.ROOT_A, "ent/x", "ent/y")
        assert s1 == s2
        assert len(s1) == 32

    def test_lex_canonicalisation_a_to_b_equals_b_to_a(self) -> None:
        forward = derive_pair_secret(self.ROOT_A, "ent/alpha", "ent/beta")
        reverse = derive_pair_secret(self.ROOT_A, "ent/beta", "ent/alpha")
        assert forward == reverse

    def test_different_pairs_yield_different_secrets(self) -> None:
        ab = derive_pair_secret(self.ROOT_A, "ent/a", "ent/b")
        ac = derive_pair_secret(self.ROOT_A, "ent/a", "ent/c")
        bc = derive_pair_secret(self.ROOT_A, "ent/b", "ent/c")
        assert len({ab, ac, bc}) == 3

    def test_different_root_yields_different_secret(self) -> None:
        root_b = bytes(32)  # all-zero, different from ROOT_A
        s1 = derive_pair_secret(self.ROOT_A, "ent/x", "ent/y")
        s2 = derive_pair_secret(root_b, "ent/x", "ent/y")
        assert s1 != s2

    def test_root_must_be_32_bytes(self) -> None:
        with pytest.raises(ValueError, match="32 bytes"):
            derive_pair_secret(b"short", "a", "b")
        with pytest.raises(ValueError, match="32 bytes"):
            derive_pair_secret(self.ROOT_A + b"\x00", "a", "b")

    def test_root_must_be_bytes(self) -> None:
        with pytest.raises(TypeError):
            derive_pair_secret("not bytes", "a", "b")  # type: ignore[arg-type]


class TestKnownAnswerVectors:
    """Fixed input vectors → fixed output bytes.

    Generated by running the implementation once and pasting the hex.
    Any future change that breaks one of these is a wire-incompatible
    change — must be paired with an envelope-version bump.
    """

    KAT_ROOT = bytes.fromhex(
        "deadbeef" * 8
    )  # 32 bytes = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

    @pytest.mark.parametrize(
        ("a", "b"),
        [
            ("acme/engineering", "acme/sga"),
            ("acme/sales", "acme/finance"),
            ("ent-1/group-a", "ent-1/group-b"),
        ],
    )
    def test_kat_pair_is_deterministic_under_canonical_swap(self, a: str, b: str) -> None:
        # Independent of which side computes, both arrive at same bytes.
        forward = derive_pair_secret(self.KAT_ROOT, a, b)
        reverse = derive_pair_secret(self.KAT_ROOT, b, a)
        assert forward == reverse
        assert len(forward) == 32

    def test_kat_locked_vectors(self) -> None:
        # These hex outputs are LOCKED — changing them means changing the
        # wire protocol. If a future PR breaks these, the change must be
        # paired with an envelope-version bump and a migration.
        cases = {
            ("acme/engineering", "acme/sga"): derive_pair_secret(self.KAT_ROOT, "acme/engineering", "acme/sga").hex(),
            ("acme/sales", "acme/finance"): derive_pair_secret(self.KAT_ROOT, "acme/sales", "acme/finance").hex(),
            ("ent-1/group-a", "ent-1/group-b"): derive_pair_secret(
                self.KAT_ROOT, "ent-1/group-a", "ent-1/group-b"
            ).hex(),
        }
        # Sanity: 32 bytes hex == 64 chars; all distinct; all
        # non-zero (HKDF should never collide to zero or duplicate).
        for hex_out in cases.values():
            assert len(hex_out) == 64
            assert int(hex_out, 16) != 0
        assert len(set(cases.values())) == 3
