// Federation tab — domain types shared across the page, drawer, and fixtures.
//
// Mirrors what we expect the directory to expose at
// `/api/v1/directory/peerings/{enterprise_id}` once agent#172's backend deps
// land. Until then, the fixtures in ./fixtures.ts populate the UI so the
// frontend can ship independently. Field names are conservative — anything we
// invent here must be reconcilable with the directory's `peering_offers`,
// `peering_acceptances`, and `consults` tables.

export type PeeringDirection = "offered-by-us" | "offered-by-them"
export type PeeringStatus =
  | "active"
  | "pending-acceptance"
  | "expiring-soon"
  | "expired"
export type OfferStatus =
  | "pending"
  | "accepted"
  | "declined"
  | "withdrawn"
  | "expired"

export interface PeerEnterprise {
  enterprise_id: string // AAISN id (e.g. "aaisn:acme-corp")
  display_name: string
}

export interface ReachabilityCheck {
  endpoint: string
  status: "ok" | "warn" | "fail"
  last_green: string | null // ISO
  last_red: string | null // ISO
  detail?: string // e.g. "SNI mismatch", "TLS handshake timeout"
}

export interface SigningKeyInfo {
  fingerprint: string // sha256:abcd...
  algorithm: string // ed25519, etc.
  rotated_at: string | null
}

export interface OfferTimelineEvent {
  ts: string
  kind: "offered" | "accepted" | "declined" | "withdrawn" | "rotated"
  by_human: string // human@enterprise display
  detail?: string
}

export interface ConsultLogBucket {
  status: "success" | "blocked" | "timeout" | "error"
  count: number
}

export interface DailyHealthPoint {
  date: string // YYYY-MM-DD
  success_rate: number // 0..1
  outbound: number
  inbound: number
}

export interface ActivePeering {
  peering_id: string
  peer: PeerEnterprise
  direction: PeeringDirection
  status: PeeringStatus
  effective_from: string
  expires_at: string
  topic_filters: string[]
  outbound_success_rate_7d: number // 0..1
  inbound_consults_7d: number
  last_round_trip_at: string | null
  // Drawer-only fields. Cheap to embed since list is small (< 50 peerings).
  reachability: {
    ours: ReachabilityCheck
    theirs: ReachabilityCheck
  }
  signing_keys: {
    ours: SigningKeyInfo
    theirs: SigningKeyInfo
  }
  offer_timeline: OfferTimelineEvent[]
  consult_log: ConsultLogBucket[]
  health_timeline_30d: DailyHealthPoint[]
  silently_broken?: SilentBreakReason | null
}

// "Silently broken" detection: peering is nominally active but health says
// otherwise. Surfaced as a banner in the drawer + a dot in the active list.
export type SilentBreakReason =
  | "dead-origin" // reachability fail for > 24h
  | "expired-key" // signing key past rotation deadline
  | "sni-mismatch" // TLS SNI cert doesn't match endpoint
  | "no-traffic-7d" // zero round-trips in 7 days despite traffic_expected

export interface PendingOffer {
  offer_id: string
  peer: PeerEnterprise
  offered_at: string
  topic_filters: string[]
  content_policy: "direct" | "summary-only" | "blocked-default"
  signature_fingerprint: string
}

export interface OutgoingOffer {
  offer_id: string
  peer: PeerEnterprise
  offered_at: string
  status: OfferStatus
  topic_filters: string[]
}

export interface MeshHealthAlarm {
  peering_id: string
  peer: PeerEnterprise
  threshold: number // 0..1
  current_rate: number // 0..1
  since: string // when it dropped
}

export interface MeshHealth {
  // Stacked area: per-day buckets across all peerings.
  daily: Array<{
    date: string
    success: number
    blocked: number
    timeout: number
    error: number
  }>
  // Heatmap rows: one per peer.
  heatmap: Array<{
    peer: PeerEnterprise
    days: Array<{ date: string; success_rate: number }>
  }>
  alarms: MeshHealthAlarm[]
}

export interface FederationView {
  this_enterprise: PeerEnterprise
  active: ActivePeering[]
  pending: PendingOffer[]
  outgoing: OutgoingOffer[]
  mesh_health: MeshHealth
  // Generated by directory; surfaces freshness in the header.
  generated_at: string
}
